name: display_mode_example
description: "Demonstrates how to use the display_mode plugin."

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  display_mode:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true